// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFG6pJfHq3kX2_Al0HjwYwDjrawjohTc0',
    appId: '1:917043349612:web:0131da0624c961391bb049',
    messagingSenderId: '917043349612',
    projectId: 'todo-875d1',
    authDomain: 'todo-875d1.firebaseapp.com',
    storageBucket: 'todo-875d1.appspot.com',
    measurementId: 'G-FS5FX1R7FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9L3iNNyMMmYKzXxyKvA6xZMeez1ljdFs',
    appId: '1:917043349612:android:cf7f9256a390865e1bb049',
    messagingSenderId: '917043349612',
    projectId: 'todo-875d1',
    storageBucket: 'todo-875d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcKByXl-cPGI-FGp-gdakt8sHZulM8Cps',
    appId: '1:917043349612:ios:61d1e590b9801bb81bb049',
    messagingSenderId: '917043349612',
    projectId: 'todo-875d1',
    storageBucket: 'todo-875d1.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcKByXl-cPGI-FGp-gdakt8sHZulM8Cps',
    appId: '1:917043349612:ios:61d1e590b9801bb81bb049',
    messagingSenderId: '917043349612',
    projectId: 'todo-875d1',
    storageBucket: 'todo-875d1.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFG6pJfHq3kX2_Al0HjwYwDjrawjohTc0',
    appId: '1:917043349612:web:632cd2a1918d43a81bb049',
    messagingSenderId: '917043349612',
    projectId: 'todo-875d1',
    authDomain: 'todo-875d1.firebaseapp.com',
    storageBucket: 'todo-875d1.appspot.com',
    measurementId: 'G-5LTHQEQKBZ',
  );
}
