// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA50eFxIhkBFg0so_smqTuCieYJMMaSMuE',
    appId: '1:439262368900:web:80e20095f4ef4dddccded1',
    messagingSenderId: '439262368900',
    projectId: 'todo-c7822',
    authDomain: 'todo-c7822.firebaseapp.com',
    storageBucket: 'todo-c7822.appspot.com',
    measurementId: 'G-23ZZT0VL10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo9D_dkOFdC4nmnOTopLp1Is9pTglLkUY',
    appId: '1:439262368900:android:7d88b7cc6d44e02eccded1',
    messagingSenderId: '439262368900',
    projectId: 'todo-c7822',
    storageBucket: 'todo-c7822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKoy7muXB411oOKVYg2YWD9_79JoKnCDQ',
    appId: '1:439262368900:ios:8d73e7077111a5ddccded1',
    messagingSenderId: '439262368900',
    projectId: 'todo-c7822',
    storageBucket: 'todo-c7822.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKoy7muXB411oOKVYg2YWD9_79JoKnCDQ',
    appId: '1:439262368900:ios:8d73e7077111a5ddccded1',
    messagingSenderId: '439262368900',
    projectId: 'todo-c7822',
    storageBucket: 'todo-c7822.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA50eFxIhkBFg0so_smqTuCieYJMMaSMuE',
    appId: '1:439262368900:web:1058a6e0ee99944dccded1',
    messagingSenderId: '439262368900',
    projectId: 'todo-c7822',
    authDomain: 'todo-c7822.firebaseapp.com',
    storageBucket: 'todo-c7822.appspot.com',
    measurementId: 'G-V51PD3WBB8',
  );

}